on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Hello world action step
      id: hello
      uses: caracha1/MyJavaScriptAction@v1
      with:
        what-to-do: "Walk on the beach"
    # Use the ouput from the hello step
    - name: Get the output day
      run: |
        echo "The day was ${{ steps.hello.outputs.day }}"
        echo "une deuxieme ligne, bravo!"